# https://docs.docker.com/engine/reference/builder/
# Docker treats lines that begin with # as a comment, unless the line is a valid parser directive.
# 使用\分行
# docker build -t component .
FROM alpine
